# Generated by Django 4.2 on 2024-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_retro_bonus_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название группы')),
                ('product', models.ManyToManyField(related_name='product_groups', to='product.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
    ]
