# Generated by Django 4.2 on 2024-04-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Главная категория', 'verbose_name_plural': 'Главные категории'},
        ),
    ]
