# Generated by Django 4.2 on 2024-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.BooleanField(default=False, verbose_name='Статус ХИТа продаж')),
                ('new', models.BooleanField(default=False, verbose_name='Статус новинки')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка на товар')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность')),
                ('product', models.ManyToManyField(related_name='parametres', to='product.product')),
            ],
        ),
    ]
