# Generated by Django 4.2 on 2024-06-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productparametr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparametr',
            name='product',
        ),
    ]
