# Generated by Django 4.2 on 2024-06-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productparametr_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parametr',
            field=models.ManyToManyField(related_name='product', to='product.productparametr'),
        ),
    ]
