# Generated by Django 4.2 on 2024-11-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_parametr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparametr',
            options={'verbose_name': 'Параметры товара', 'verbose_name_plural': 'Параметры товаров'},
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название фото')),
                ('photo', models.ImageField(upload_to='products_img', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='product.product', verbose_name='Фотографии товара')),
            ],
            options={
                'verbose_name': 'verbose_name',
                'verbose_name_plural': 'verbose_name_plural',
            },
        ),
    ]
