# Generated by Django 4.2 on 2024-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productparametr_options_productphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='products_img/more', verbose_name='Фото'),
        ),
    ]
