# Generated by Django 4.2 on 2024-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('desc', models.TextField(verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d', verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('slug', models.SlugField(max_length=255, verbose_name='')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
