# Generated by Django 4.2 on 2024-05-04 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='retro_bonus_balance',
            field=models.IntegerField(default=0, verbose_name='Сумма бонусов клиента'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_bonus_balance', models.IntegerField(default=0, verbose_name='Сумма бонусов клиента')),
                ('delivery_address', models.TextField(max_length=3000, verbose_name='Адресс достаавки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Юзер инфо',
                'verbose_name_plural': 'Юзер инфо',
            },
        ),
    ]
