# Generated by Django 4.2 on 2024-05-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='counties_flags/', verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Страна производителя',
                'verbose_name_plural': 'Страны производителей',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('image', models.ImageField(upload_to='manufacturer/', verbose_name='Логотип')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacurers', to='manufacturer.manufacturercountry', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
