# Generated by Django 4.2 on 2024-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'verbose_name': 'Слайдер на главной странице', 'verbose_name_plural': 'Слайдер на главной странице'},
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(help_text='Максимальное разрешение изображения 2400х600px', upload_to='special_offers/%Y/%m', verbose_name='Фото'),
        ),
    ]
